[package]
name = "pilatus-emulation-camera-rt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
futures.workspace = true
image = { workspace = true, optional = true }
minfac = { workspace = true, optional = true }
pilatus.workspace = true
pilatus-engineering = { path = "../pilatus-engineering", features = ["image-algorithm"] }
pilatus-axum.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["sync"], optional = true }
tokio-stream = { version = "0.1", features = ["fs", "sync"], optional = true }
tracing.workspace = true

# dev-dependencies cannot be optional
tempfile = { version = "3", optional = true }
serde_json = { version = "1", optional = true }
pilatus-rt = { workspace = true, features = ["unstable"], optional = true }

[dev-dependencies]
pilatus-emulation-camera-rt = { path = ".", features = ["rt"] }
tokio = { workspace = true, features = ["sync", "macros"]}

[features]
rt = ["pilatus/tokio", "dep:image", "dep:minfac", "tokio", "tokio-stream"]
integration = ["tempfile", "serde_json", "pilatus-rt"]
unstable = []